feat: allow to import require statements and show all failing with mu…
loft-sh/devspace pull request #2354
Opened 2022-09-30 04:13 UTC by dtomasi

…ltierror

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2353

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace does not resolve `require` recursive in `imports`. Additionally this introduces mutlierror for requirements to output all unmet requirements at once. This is useful if there are a bunch of imports with different requirements.

**What else do we need to know?**

2022-09-30 15:48 UTC, lizardruss requested changes
Thanks for the PR!

See my inline comments for requested changes

2022-10-01 13:41 UTC, dtomasi commented on pkg/devspace/config/loader/loader.go
> +	"github.com/hashicorp/go-multierror"
@lizardruss thanks. wasn't aware of the kube package.

2022-10-03 08:18 UTC, FabianKramm approved these changes
@dtomasi thanks for the PR! LGTM!

2022-10-03 10:03 UTC, FabianKramm commented
@dtomasi unfortunately the tests are failing, please take a look there!

2022-10-04 03:41 UTC, dtomasi commented
@FabianKramm well ... a stupid mistake in variable assignment caused this. Unfortunately, I cannot see if everything passes now now, as of

> First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

However ... Hope this fixes the tests.

2022-10-04 16:17 UTC, lizardruss approved these changes

2022-10-05 17:02 UTC, merged