fix: Imported variables are not used in other variables
loft-sh/devspace pull request #2432
Opened 2022-11-17 13:42 UTC by pratikjagrut

**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #2408 

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace was not using imported variables in defining another variable in main devspace.yaml

2022-11-17 19:34 UTC, lizardruss requested changes
There could be unexpected behavior with the current implementation. I'll ask for a second opinion as well.

2022-11-17 19:34 UTC, lizardruss commented on pkg/devspace/config/loader/variable/resolver.go
> +	}
This might make it so the importer cannot set a variable to `""`.

2022-11-17 19:34 UTC, lizardruss commented on e2e/tests/imports/testdata/conditional/devspace.yaml
> +    command: echo ${NEW_MESSAGE}
Can we add a case for when both have a var with the same name, where the importer sets the value to `""`?

I suspect that the imported value would be used over the local value, which may be unexpected.

2022-11-21 13:55 UTC, FabianKramm approved these changes

2022-11-21 13:55 UTC, merged